name: Test and Push to Container Registry

on:
  push:
    branches: [ main ]

jobs:
  test_and_push_to_registry:
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
      matrix: 
        python-version: [3.9]
        language: ['python']
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@master
    - name: Initialize Python 3.9
      uses: actions/setup-python@v1
      with: 
        python-version: ${{matrix.python-version}}
    - name: Install Dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    - name: Run tests
      run: |
        . venv/bin/activate
        python3 -m pytest
        # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}  
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1  
    - name: Push to DockerHub
      uses: docker/build-push-action/@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: ${{secrets.DOCKERHUB_REPO}}
        tag_with_sha: true
  
